/**
 * Enum for product categories.
 */
export enum ProductCategory {
  SALADS = "SALADS",
  GARNISH_AND_EXTRA = "GARNISH_AND_EXTRA",
  APPETIZERS = "APPETIZERS",
  GRILL = "GRILL",
  DISHES_TO_ORDER = "DISHES_TO_ORDER",
  SPECIALITIES = "SPECIALITIES",
  COOKED_DISHES = "COOKED_DISHES",
  DESSERTS = "DESSERTS",
  SNACKS = "SNACKS",
  APERATIVES = "APERATIVES",
  DRINKS = "DRINKS",
}
